name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your default branch if it's not 'main'
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        env:
          VITE_API_LOCAL: ${{ vars.VITE_API_LOCAL }}
        run: pnpm run build --filter=web-ui

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload dist repository
          path: "./apps/web-ui/dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
